-- SQL to run

-- 1)
insert into storage.buckets (id, name, public) 
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  headline text,
  sub_headline text,
  profile_image text default 'profile.jpg',
  ticker_speed integer default 3500,
  resume_file text,
  linkedin_url text,
  show_linkedin boolean default true,
  facebook_url text,
  show_facebook boolean default false,
  instagram_url text,
  show_instagram boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.experiences (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  company text not null,
  role text not null,
  duration text not null,
  description text,
  color_class text default 'bg-blue-600',
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.education (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  degree text not null,
  field text not null,
  institution text not null,
  year text not null,
  type text not null,
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.endorsements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  role text not null,
  text text not null,
  color_class text default 'from-blue-500 to-blue-700',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  text text not null,
  done boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.profiles enable row level security;
alter table public.experiences enable row level security;
alter table public.education enable row level security;
alter table public.endorsements enable row level security;
alter table public.goals enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Public experiences are viewable by everyone." on public.experiences for select using (true);
create policy "Public education are viewable by everyone." on public.education for select using (true);
create policy "Public endorsements are viewable by everyone." on public.endorsements for select using (true);

create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);

create policy "Users can insert their own experience." on public.experiences for insert with check (auth.uid() = user_id);
create policy "Users can update their own experience." on public.experiences for update using (auth.uid() = user_id);
create policy "Users can delete their own experience." on public.experiences for delete using (auth.uid() = user_id);

create policy "Users can insert their own education." on public.education for insert with check (auth.uid() = user_id);
create policy "Users can update their own education." on public.education for update using (auth.uid() = user_id);
create policy "Users can delete their own education." on public.education for delete using (auth.uid() = user_id);

create policy "Users can insert their own endorsements." on public.endorsements for insert with check (auth.uid() = user_id);
create policy "Users can update their own endorsements." on public.endorsements for update using (auth.uid() = user_id);
create policy "Users can delete their own endorsements." on public.endorsements for delete using (auth.uid() = user_id);

create policy "Users can see their own goals." on public.goals for select using (auth.uid() = user_id);
create policy "Users can insert their own goals." on public.goals for insert with check (auth.uid() = user_id);
create policy "Users can update their own goals." on public.goals for update using (auth.uid() = user_id);
create policy "Users can delete their own goals." on public.goals for delete using (auth.uid() = user_id);

create policy "Portfolio images are publicly accessible." on storage.objects for select using (bucket_id = 'portfolio');
create policy "Users can upload portfolio images." on storage.objects for insert with check (bucket_id = 'portfolio' and auth.role() = 'authenticated');
create policy "Users can delete portfolio images." on storage.objects for delete using (bucket_id = 'portfolio' and auth.role() = 'authenticated');

-- 2)
ALTER TABLE public.endorsements 
ADD COLUMN linkedin_url text,
ADD COLUMN image_url text;


