-- SQL to run

-- 1)
insert into storage.buckets (id, name, public) 
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  headline text,
  sub_headline text,
  profile_image text default 'profile.jpg',
  ticker_speed integer default 3500,
  resume_file text,
  linkedin_url text,
  show_linkedin boolean default true,
  facebook_url text,
  show_facebook boolean default false,
  instagram_url text,
  show_instagram boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.experiences (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  company text not null,
  role text not null,
  duration text not null,
  description text,
  color_class text default 'bg-blue-600',
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.education (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  degree text not null,
  field text not null,
  institution text not null,
  year text not null,
  type text not null,
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.endorsements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  role text not null,
  text text not null,
  color_class text default 'from-blue-500 to-blue-700',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  text text not null,
  done boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.profiles enable row level security;
alter table public.experiences enable row level security;
alter table public.education enable row level security;
alter table public.endorsements enable row level security;
alter table public.goals enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Public experiences are viewable by everyone." on public.experiences for select using (true);
create policy "Public education are viewable by everyone." on public.education for select using (true);
create policy "Public endorsements are viewable by everyone." on public.endorsements for select using (true);

create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);

create policy "Users can insert their own experience." on public.experiences for insert with check (auth.uid() = user_id);
create policy "Users can update their own experience." on public.experiences for update using (auth.uid() = user_id);
create policy "Users can delete their own experience." on public.experiences for delete using (auth.uid() = user_id);

create policy "Users can insert their own education." on public.education for insert with check (auth.uid() = user_id);
create policy "Users can update their own education." on public.education for update using (auth.uid() = user_id);
create policy "Users can delete their own education." on public.education for delete using (auth.uid() = user_id);

create policy "Users can insert their own endorsements." on public.endorsements for insert with check (auth.uid() = user_id);
create policy "Users can update their own endorsements." on public.endorsements for update using (auth.uid() = user_id);
create policy "Users can delete their own endorsements." on public.endorsements for delete using (auth.uid() = user_id);

create policy "Users can see their own goals." on public.goals for select using (auth.uid() = user_id);
create policy "Users can insert their own goals." on public.goals for insert with check (auth.uid() = user_id);
create policy "Users can update their own goals." on public.goals for update using (auth.uid() = user_id);
create policy "Users can delete their own goals." on public.goals for delete using (auth.uid() = user_id);

create policy "Portfolio images are publicly accessible." on storage.objects for select using (bucket_id = 'portfolio');
create policy "Users can upload portfolio images." on storage.objects for insert with check (bucket_id = 'portfolio' and auth.role() = 'authenticated');
create policy "Users can delete portfolio images." on storage.objects for delete using (bucket_id = 'portfolio' and auth.role() = 'authenticated');

-- 2)
ALTER TABLE public.endorsements 
ADD COLUMN linkedin_url text,
ADD COLUMN image_url text;


-- 3)
ALTER TABLE public.profiles 
ADD COLUMN hero_title text DEFAULT 'Sudeep<br>Dalal',
ADD COLUMN hero_subtitle text DEFAULT 'Assistant Manager<br>Procurement & Supply Chain';

-- 4
ALTER TABLE public.profiles 
ADD COLUMN theme text DEFAULT 'default',
ADD COLUMN font_family text DEFAULT 'Inter',
ADD COLUMN custom_font_url text;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('fonts', 'fonts', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Fonts are publicly accessible." ON storage.objects FOR SELECT USING (bucket_id = 'fonts');
CREATE POLICY "Users can upload fonts." ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'fonts' AND auth.role() = 'authenticated');


  -- 4
ALTER TABLE public.profiles 
ADD COLUMN projects_view_layout text DEFAULT 'list'; 

CREATE TABLE public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  experience_id bigint references public.experiences on delete cascade, 
  title text not null,
  short_description text,
  long_description text,
  images text[], 
  layout_type text DEFAULT 'standard',
  order_index integer DEFAULT 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public projects are viewable by everyone." 
  ON public.projects FOR SELECT USING (true);

CREATE POLICY "Users can insert their own projects." 
  ON public.projects FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own projects." 
  ON public.projects FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own projects." 
  ON public.projects FOR DELETE USING (auth.uid() = user_id);

  -- 5
ALTER TABLE public.profiles 
ADD COLUMN projects_header_title text DEFAULT 'Selected Works',
ADD COLUMN projects_header_subtitle text DEFAULT 'A collection of strategic initiatives and sourcing projects.';

-- 6
CREATE TABLE public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null,
  summary text,
  content text,
  image_url text,
  layout_type text DEFAULT 'classic',
  is_published boolean DEFAULT false,
  show_date boolean DEFAULT true,
  show_author boolean DEFAULT true,
  published_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public posts are viewable by everyone." 
  ON public.posts FOR SELECT USING (true);

CREATE POLICY "Users can insert their own posts." 
  ON public.posts FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own posts." 
  ON public.posts FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own posts." 
  ON public.posts FOR DELETE USING (auth.uid() = user_id);

  -- 7
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS summary text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS layout_type text DEFAULT 'classic';
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS is_published boolean DEFAULT false;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS show_date boolean DEFAULT true;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS show_author boolean DEFAULT true;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS published_at timestamp with time zone DEFAULT timezone('utc'::text, now());

DROP POLICY IF EXISTS "Public posts are viewable by everyone." ON public.posts;
DROP POLICY IF EXISTS "Users can insert their own posts." ON public.posts;
DROP POLICY IF EXISTS "Users can update their own posts." ON public.posts;
DROP POLICY IF EXISTS "Users can delete their own posts." ON public.posts;

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public posts are viewable by everyone." 
  ON public.posts FOR SELECT USING (true);

CREATE POLICY "Users can insert their own posts." 
  ON public.posts FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own posts." 
  ON public.posts FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own posts." 
  ON public.posts FOR DELETE USING (auth.uid() = user_id);

  -- 8
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS insights_header_title text DEFAULT 'Insights.',
ADD COLUMN IF NOT EXISTS insights_header_subtitle text DEFAULT 'Thoughts on strategic sourcing, market trends, and supply chain management.';

-- 9

create table public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  is_read boolean default false,
  is_saved boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.contact_messages enable row level security;

create policy "Public can send messages" 
  on public.contact_messages for insert with check (true);

create policy "Admins can manage messages" 
  on public.contact_messages for all using (auth.role() = 'authenticated');

  -- 10
create table public.analytics_visits (
  id bigint generated by default as identity primary key,
  path text not null,
  ip_address text,
  country text,
  city text,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.analytics_visits enable row level security;

create policy "Anyone can log visits" on public.analytics_visits for insert with check (true);
create policy "Admins view analytics" on public.analytics_visits for select using (auth.role() = 'authenticated');

create or replace view public.storage_usage as
select 
  sum((metadata->>'size')::bigint) as total_bytes,
  count(*) as file_count
from storage.objects;

grant select on public.storage_usage to authenticated;